apple_resource(
    name = "TicTacToeAppStringResources",
    visibility = ["//App:"],
    files = [],
    variants = glob([
        "*.lproj/TicTacToeApp.strings",
    ]),
)

apple_resource(
    name = "StoryboardResources",
    visibility = ["//App:"],
    variants = glob([
        "*.lproj/*.storyboard",
    ]),
)
