load("//Config:buck_rule_macros.bzl", "first_party_library")

first_party_library(
    name = "LoggedInPluginPoint",
    deps = [
        "//Pods:NeedleFoundation",
        "//Libraries/ScoreSheet:ScoreSheet",
        "//Libraries/Models:Models",
    ],
)