load("//Config:buck_rule_macros.bzl", "first_party_library")

first_party_library(
    name = "CarthageDeps",
    deps = [
        "//Carthage:RIBs",
        "//Carthage:RxSwift",
        "//Carthage:RxCocoa",
        "//Carthage:NeedleFoundation",
    ]
)
